import type { CourseTrack } from "../../libs/learn/types";

export const COURSE_TRACKS: CourseTrack[] = [
  {
    id: "salvation",
    title: "Salvation",
    description: "Understand the gift of eternal life through Jesus Christ.",
    lessons: [
      {
        id: "salvation-1",
        title: "For God So Loved",
        scripture: "John 3:16",
        verse: "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.",
        body: "Salvation begins not with human effort but with divine love. God initiated our rescue before we even knew we needed it. The Cross is the supreme expression of that love — costly, voluntary, complete.",
        reflection: "When did you first realize that God's love for you was personal, not just general?",
      },
      {
        id: "salvation-2",
        title: "All Have Sinned",
        scripture: "Romans 3:23",
        verse: "For all have sinned and fall short of the glory of God.",
        body: "The diagnosis precedes the cure. Sin is not merely bad behavior — it is the broken relationship between humanity and our Creator. Recognizing our need is the first step toward receiving grace.",
        reflection: "In what areas of your life do you most clearly sense your need for God?",
      },
      {
        id: "salvation-3",
        title: "The Gift of Life",
        scripture: "Romans 6:23",
        verse: "For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.",
        body: "Wages are earned; gifts are received. Eternal life cannot be earned by religious performance — it is freely given to those who trust in Christ. This distinction changes how we approach God.",
        reflection: "How does receiving salvation as a gift (not wages) change how you relate to God today?",
      },
      {
        id: "salvation-4",
        title: "Confess and Believe",
        scripture: "Romans 10:9",
        verse: "If you declare with your mouth, \"Jesus is Lord,\" and believe in your heart that God raised him from the dead, you will be saved.",
        body: "Salvation is as simple as a confession and a conviction. The resurrection is the hinge of history — if Jesus rose, everything He said is true. The heart that believes and the mouth that confesses are together the door to new life.",
        reflection: "What does it mean practically for you to declare \"Jesus is Lord\" in your daily decisions?",
      },
      {
        id: "salvation-5",
        title: "The Prodigal Returns",
        scripture: "Luke 15:20",
        verse: "But while he was still a long way off, his father saw him and was filled with compassion for him; he ran to his son, threw his arms around him and kissed him.",
        body: "The father in this parable does not wait at the door — he runs. This portrait of God shows that repentance is met not with reluctant acceptance but with exuberant joy. No distance is too great for His love to close.",
        reflection: "Is there anything that makes you feel too far from God right now? What would it mean to take one step back toward Him?",
      },
    ],
  },

  {
    id: "prayer",
    title: "Prayer",
    description: "Learn to commune with the Father through Scripture-grounded prayer.",
    lessons: [
      {
        id: "prayer-1",
        title: "The Lord's Prayer",
        scripture: "Matthew 6:9-10",
        verse: "Our Father in heaven, hallowed be your name, your kingdom come, your will be done, on earth as it is in heaven.",
        body: "Jesus gave us a pattern, not a formula. Prayer starts with who God is — Father, holy, sovereign — before turning to our needs. Aligning our desires with His kingdom is the posture that transforms our asking.",
        reflection: "When you pray, do you spend more time on God's glory or your own requests? How might the Lord's Prayer reorder that?",
      },
      {
        id: "prayer-2",
        title: "Ask, Seek, Knock",
        scripture: "Matthew 7:7-8",
        verse: "Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.",
        body: "Jesus calls us to persistent, expectant prayer. The three verbs are progressive — asking is a single request, seeking involves intentional pursuit, knocking persists at a shut door. God rewards those who press in.",
        reflection: "What door have you stopped knocking on? What might God be calling you to return to in prayer?",
      },
      {
        id: "prayer-3",
        title: "Pray Without Ceasing",
        scripture: "1 Thessalonians 5:17",
        verse: "Pray continually.",
        body: "Two words, infinite depth. Unceasing prayer is not a life of closed eyes and bowed heads — it is a heart continuously turned toward God. Every moment becomes an opportunity for communion.",
        reflection: "How could you weave one moment of conscious prayer into an activity you do every day this week?",
      },
      {
        id: "prayer-4",
        title: "The Spirit Intercedes",
        scripture: "Romans 8:26",
        verse: "In the same way, the Spirit helps us in our weakness. We do not know what we ought to pray for, but the Spirit himself intercedes for us through wordless groans.",
        body: "You don't need perfect words to pray — the Holy Spirit translates even your groans to the Father. In seasons of confusion, grief, or exhaustion, this promise is a great anchor: you are never praying alone.",
        reflection: "When you feel too weak or confused to pray, how does knowing the Spirit intercedes for you change your posture?",
      },
      {
        id: "prayer-5",
        title: "The Garden of Surrender",
        scripture: "Matthew 26:39",
        verse: "My Father, if it is possible, may this cup be taken from me. Yet not as I will, but as you will.",
        body: "The most honest prayer Jesus ever prayed included a request He did not want to make and a surrender He chose anyway. Bring your real feelings, then align your will to the Father. Surrender is not weakness — it is the highest form of trust.",
        reflection: "Is there a situation you're praying about where you need to say \"yet not my will\"? What makes that hard?",
      },
    ],
  },

  {
    id: "grace",
    title: "Grace",
    description: "Discover the scandalous, limitless grace of God.",
    lessons: [
      {
        id: "grace-1",
        title: "Saved by Grace",
        scripture: "Ephesians 2:8-9",
        verse: "For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God — not by works, so that no one can boast.",
        body: "Grace removes every ground for human boasting. Salvation is 100% God's initiative, received through faith, not earned through effort. This liberates us from the exhausting cycle of trying to earn God's acceptance.",
        reflection: "Where in your life do you still try to earn God's favor rather than receive His grace?",
      },
      {
        id: "grace-2",
        title: "Where Sin Abounded",
        scripture: "Romans 5:20",
        verse: "The law was brought in so that the trespass might increase. But where sin increased, grace increased all the more.",
        body: "Grace is not a small thing. It is greater than the sum of all human failure. No sin is too great, no history too dark, for the grace of God to cover. This is not license to sin — it is an invitation to marvel.",
        reflection: "Has your sense of your own unworthiness ever made you doubt that grace could cover you? How does Romans 5:20 speak to that?",
      },
      {
        id: "grace-3",
        title: "The Adulterous Woman",
        scripture: "John 8:10-11",
        verse: "Then neither do I condemn you, Jesus declared. Go now and leave your life of sin.",
        body: "Jesus did something radical: He first removed condemnation, then issued the call to transformation. Grace precedes moral instruction — it is the power that makes change possible, not a reward for having changed.",
        reflection: "Do you tend to experience Jesus as the one who condemns you or the one who says \"neither do I condemn you\"? Why?",
      },
      {
        id: "grace-4",
        title: "Sufficient Grace",
        scripture: "2 Corinthians 12:9",
        verse: "My grace is sufficient for you, for my power is made perfect in weakness. Therefore I will boast all the more gladly about my weaknesses, so that Christ's power may rest on me.",
        body: "Paul received not the removal of his thorn but the assurance of sufficient grace. Sometimes God's answer is not deliverance but deeper dependence. Our weakness becomes the canvas on which His strength is displayed.",
        reflection: "What thorn in your life might God be using to deepen your dependence on His grace?",
      },
      {
        id: "grace-5",
        title: "Grace that Trains",
        scripture: "Titus 2:11-12",
        verse: "For the grace of God has appeared that offers salvation to all people. It teaches us to say No to ungodliness and worldly passions, and to live self-controlled, upright and godly lives.",
        body: "Grace is not passive — it trains. The same grace that saves us disciplines us. This dismantles the false fear that emphasizing grace will lead to lawlessness. True grace produces godliness, not indifference to sin.",
        reflection: "How has experiencing God's grace in a specific area of your life actually made you want to change?",
      },
    ],
  },

  {
    id: "identity",
    title: "Identity in Christ",
    description: "Discover who you truly are as a new creation in Jesus.",
    lessons: [
      {
        id: "identity-1",
        title: "New Creation",
        scripture: "2 Corinthians 5:17",
        verse: "Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!",
        body: "In Christ, you are not a reformed version of your old self — you are a fundamentally new creation. Old shame, old labels, old failures do not define you. Your identity is now bound to who Jesus is, not what you have done.",
        reflection: "What old label or identity do you most need to let go of in light of your new creation identity?",
      },
      {
        id: "identity-2",
        title: "Children of God",
        scripture: "1 John 3:1",
        verse: "See what great love the Father has lavished on us, that we should be called children of God! And that is what we are!",
        body: "You are not a servant, not merely a creation — you are a dearly loved child of God. John exclaims this truth as if he still can't quite believe it. This is the relational reality you live from.",
        reflection: "How would your daily life change if you walked through each moment as a genuinely loved child of God?",
      },
      {
        id: "identity-3",
        title: "The Vine and Branches",
        scripture: "John 15:5",
        verse: "I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit; apart from me you can do nothing.",
        body: "Your identity in Christ is not only about what you are called but about where you are connected. The branch has no life independent of the vine. Fruitfulness flows from abiding — from staying close to Jesus, not striving harder.",
        reflection: "What does abiding in Christ look like practically in your current season of life?",
      },
      {
        id: "identity-4",
        title: "I Can Do All Things",
        scripture: "Philippians 4:13",
        verse: "I can do all this through him who gives me strength.",
        body: "Paul wrote from prison about learning contentment in all circumstances. The strength promised is not for unlimited ambition — it is the grace to face any situation from a place of peace and sufficiency in Christ.",
        reflection: "In which current circumstances do you need to draw on Christ's strength rather than your own?",
      },
      {
        id: "identity-5",
        title: "Royal Priesthood",
        scripture: "1 Peter 2:9",
        verse: "But you are a chosen people, a royal priesthood, a holy nation, God's special possession, that you may declare the praises of him who called you out of darkness into his wonderful light.",
        body: "Peter uses four layers of identity: chosen, royal, holy, possessed. You were not an afterthought — you were specifically selected for a purpose. Your existence declares the glory of the One who called you out of darkness.",
        reflection: "Which of these four identity descriptions — chosen, royal, holy, special possession — is hardest for you to receive? Why?",
      },
    ],
  },

  {
    id: "warfare",
    title: "Spiritual Warfare",
    description: "Stand firm against the enemy with the full armor of God.",
    lessons: [
      {
        id: "warfare-1",
        title: "The Armor of God",
        scripture: "Ephesians 6:10-11",
        verse: "Finally, be strong in the Lord and in his mighty power. Put on the full armor of God, so that you can take your stand against the devil's schemes.",
        body: "Spiritual warfare begins with the recognition that our strength is not our own — it is the Lord's. The armor is not self-protection; it is divine provision. Every piece directs us toward God: truth, righteousness, faith, salvation, the Word.",
        reflection: "Which piece of the armor do you feel is currently missing or neglected in your life?",
      },
      {
        id: "warfare-2",
        title: "Thief vs Shepherd",
        scripture: "John 10:10",
        verse: "The thief comes only to steal and kill and destroy; I have come that they may have life, and have it to the full.",
        body: "Understanding the enemy's agenda clarifies the battle. When life feels diminished, stolen, or destroyed — recognize the source. Jesus came not just to preserve life but to fill it to overflowing. The war is between two agendas.",
        reflection: "In what area of your life do you most recognize the thief's work right now? How does the Shepherd's promise speak into it?",
      },
      {
        id: "warfare-3",
        title: "Greater is He",
        scripture: "1 John 4:4",
        verse: "You, dear children, are from God and have overcome them, because the one who is in you is greater than the one who is in the world.",
        body: "The victory is positional before it is experiential. Because the Spirit of God dwells in you, you are already on the winning side. Spiritual warfare is not fighting for victory — it is enforcing a victory already secured at the Cross.",
        reflection: "How does knowing the battle is already won (not just to be won) change how you face spiritual opposition?",
      },
      {
        id: "warfare-4",
        title: "Submit and Resist",
        scripture: "James 4:7",
        verse: "Submit yourselves, then, to God. Resist the devil, and he will flee from you.",
        body: "The order matters: submit first, then resist. Resistance without submission is willpower. Submission before resistance is spiritual authority. The devil does not flee from human determination — he flees from the presence and authority of God in you.",
        reflection: "Is there an area where you have been trying to resist the enemy without first submitting that area fully to God?",
      },
      {
        id: "warfare-5",
        title: "Weapons of Our Warfare",
        scripture: "2 Corinthians 10:4",
        verse: "The weapons we fight with are not the weapons of the world. On the contrary, they have divine power to demolish strongholds.",
        body: "Our weapons are not political, social, or psychological — they are spiritual. Prayer, the Word of God, worship, fasting, and the declaration of truth are stronger than any human strategy. Strongholds are demolished by divine power wielded through obedience.",
        reflection: "What stronghold in your thinking or habits needs demolishing? Which spiritual weapon will you take up this week?",
      },
    ],
  },
];

export function getTrackById(id: string): CourseTrack | undefined {
  return COURSE_TRACKS.find((t) => t.id === id);
}
