export type BibleBook = {
  name: string;
  abbr: string;
  chapters: number;
};

export const BIBLE_BOOKS: BibleBook[] = [
  // Old Testament
  { name: 'Genesis', abbr: 'Gen', chapters: 50 },
  { name: 'Exodus', abbr: 'Exod', chapters: 40 },
  { name: 'Leviticus', abbr: 'Lev', chapters: 27 },
  { name: 'Numbers', abbr: 'Num', chapters: 36 },
  { name: 'Deuteronomy', abbr: 'Deut', chapters: 34 },
  { name: 'Joshua', abbr: 'Josh', chapters: 24 },
  { name: 'Judges', abbr: 'Judg', chapters: 21 },
  { name: 'Ruth', abbr: 'Ruth', chapters: 4 },
  { name: '1 Samuel', abbr: '1Sam', chapters: 31 },
  { name: '2 Samuel', abbr: '2Sam', chapters: 24 },
  { name: '1 Kings', abbr: '1Kgs', chapters: 22 },
  { name: '2 Kings', abbr: '2Kgs', chapters: 25 },
  { name: '1 Chronicles', abbr: '1Chr', chapters: 29 },
  { name: '2 Chronicles', abbr: '2Chr', chapters: 36 },
  { name: 'Ezra', abbr: 'Ezra', chapters: 10 },
  { name: 'Nehemiah', abbr: 'Neh', chapters: 13 },
  { name: 'Esther', abbr: 'Esth', chapters: 10 },
  { name: 'Job', abbr: 'Job', chapters: 42 },
  { name: 'Psalms', abbr: 'Ps', chapters: 150 },
  { name: 'Proverbs', abbr: 'Prov', chapters: 31 },
  { name: 'Ecclesiastes', abbr: 'Eccl', chapters: 12 },
  { name: 'Song of Solomon', abbr: 'Song', chapters: 8 },
  { name: 'Isaiah', abbr: 'Isa', chapters: 66 },
  { name: 'Jeremiah', abbr: 'Jer', chapters: 52 },
  { name: 'Lamentations', abbr: 'Lam', chapters: 5 },
  { name: 'Ezekiel', abbr: 'Ezek', chapters: 48 },
  { name: 'Daniel', abbr: 'Dan', chapters: 12 },
  { name: 'Hosea', abbr: 'Hos', chapters: 14 },
  { name: 'Joel', abbr: 'Joel', chapters: 3 },
  { name: 'Amos', abbr: 'Amos', chapters: 9 },
  { name: 'Obadiah', abbr: 'Obad', chapters: 1 },
  { name: 'Jonah', abbr: 'Jonah', chapters: 4 },
  { name: 'Micah', abbr: 'Mic', chapters: 7 },
  { name: 'Nahum', abbr: 'Nah', chapters: 3 },
  { name: 'Habakkuk', abbr: 'Hab', chapters: 3 },
  { name: 'Zephaniah', abbr: 'Zeph', chapters: 3 },
  { name: 'Haggai', abbr: 'Hag', chapters: 2 },
  { name: 'Zechariah', abbr: 'Zech', chapters: 14 },
  { name: 'Malachi', abbr: 'Mal', chapters: 4 },
  // New Testament
  { name: 'Matthew', abbr: 'Matt', chapters: 28 },
  { name: 'Mark', abbr: 'Mark', chapters: 16 },
  { name: 'Luke', abbr: 'Luke', chapters: 24 },
  { name: 'John', abbr: 'John', chapters: 21 },
  { name: 'Acts', abbr: 'Acts', chapters: 28 },
  { name: 'Romans', abbr: 'Rom', chapters: 16 },
  { name: '1 Corinthians', abbr: '1Cor', chapters: 16 },
  { name: '2 Corinthians', abbr: '2Cor', chapters: 13 },
  { name: 'Galatians', abbr: 'Gal', chapters: 6 },
  { name: 'Ephesians', abbr: 'Eph', chapters: 6 },
  { name: 'Philippians', abbr: 'Phil', chapters: 4 },
  { name: 'Colossians', abbr: 'Col', chapters: 4 },
  { name: '1 Thessalonians', abbr: '1Thess', chapters: 5 },
  { name: '2 Thessalonians', abbr: '2Thess', chapters: 3 },
  { name: '1 Timothy', abbr: '1Tim', chapters: 6 },
  { name: '2 Timothy', abbr: '2Tim', chapters: 4 },
  { name: 'Titus', abbr: 'Titus', chapters: 3 },
  { name: 'Philemon', abbr: 'Phlm', chapters: 1 },
  { name: 'Hebrews', abbr: 'Heb', chapters: 13 },
  { name: 'James', abbr: 'Jas', chapters: 5 },
  { name: '1 Peter', abbr: '1Pet', chapters: 5 },
  { name: '2 Peter', abbr: '2Pet', chapters: 3 },
  { name: '1 John', abbr: '1John', chapters: 5 },
  { name: '2 John', abbr: '2John', chapters: 1 },
  { name: '3 John', abbr: '3John', chapters: 1 },
  { name: 'Jude', abbr: 'Jude', chapters: 1 },
  { name: 'Revelation', abbr: 'Rev', chapters: 22 },
];

/** Maximum verse number ever found in any chapter of the Bible (Psalm 119). */
export const MAX_VERSE = 176;
