// Static registry of curated Christian books
// Stage 4A

export interface Book {
  id: string;
  title: string;
  author: string;
  description: string;
  genre: string;
  topics: string[];
  coverColor: string;
  url: string;
  quotes: [string, string, string];
}

export const CHRISTIAN_BOOKS: Book[] = [
  {
    id: 'mere-christianity',
    title: 'Mere Christianity',
    author: 'C.S. Lewis',
    description: 'A foundational defense of the Christian faith, exploring morality, faith, and the nature of God.',
    genre: 'Apologetics',
    topics: ['theology', 'apologetics'],
    coverColor: '#7c3aed',
    url: 'https://www.goodreads.com/book/show/11138.Mere_Christianity',
    quotes: [
      'If I find in myself desires which nothing in this world can satisfy, the only logical explanation is that I was made for another world.',
      'Christianity, if false, is of no importance, and if true, of infinite importance. The only thing it cannot be is moderately important.',
      'God cannot give us a happiness and peace apart from Himself, because it is not there. There is no such thing.',
    ],
  },
  {
    id: 'purpose-driven-life',
    title: 'The Purpose Driven Life',
    author: 'Rick Warren',
    description: 'A 40-day journey to discovering God\'s purpose for your life.',
    genre: 'Devotional',
    topics: ['purpose', 'identity'],
    coverColor: '#f59e0b',
    url: 'https://www.goodreads.com/book/show/98880.The_Purpose_Driven_Life',
    quotes: [
      'It\'s not about you.',
      'You were made by God and for God — and until you understand that, life will never make sense.',
      'The greatest tragedy is not death, but life without purpose.',
    ],
  },
  {
    id: 'crazy-love',
    title: 'Crazy Love',
    author: 'Francis Chan',
    description: 'A call to stop living a lukewarm faith and pursue radical love for God.',
    genre: 'Discipleship',
    topics: ['discipleship', 'grace', 'identity'],
    coverColor: '#0ea5e9',
    url: 'https://www.goodreads.com/book/show/3241748-crazy-love',
    quotes: [
      'Stop asking God to bless what you\'re doing. Get involved in what God is doing — because it\'s already blessed.',
      'Our greatest fear should not be of failure but of succeeding at things in life that don\'t really matter.',
      'God is calling you to a passionate love relationship with Himself, not a lifeless list of rules.',
    ],
  },
  {
    id: 'knowing-god',
    title: 'Knowing God',
    author: 'J.I. Packer',
    description: 'A classic exploration of the attributes of God and what it means to truly know Him.',
    genre: 'Theology',
    topics: ['theology', 'prayer'],
    coverColor: '#6366f1',
    url: 'https://www.goodreads.com/book/show/158164.Knowing_God',
    quotes: [
      'What were we made for? To know God.',
      'Knowing God is crucially important for the living of our lives.',
      'Once you become aware that the main business that you are here for is to know God, most of life\'s problems fall into place of their own accord.',
    ],
  },
  {
    id: 'celebration-discipline',
    title: 'Celebration of Discipline',
    author: 'Richard Foster',
    description: 'A guide to the inward, outward, and corporate spiritual disciplines.',
    genre: 'Spiritual Formation',
    topics: ['prayer', 'discipline', 'discipleship'],
    coverColor: '#10b981',
    url: 'https://www.goodreads.com/book/show/102861.Celebration_of_Discipline',
    quotes: [
      'Superficiality is the curse of our age. The desperate need today is not for a greater number of intelligent people, or gifted people, but for deep people.',
      'The purpose of the disciplines is liberation from the stifling slavery to self-interest and fear.',
      'Joy is the keynote of all the disciplines. The fruit of the Spirit is joy.',
    ],
  },
  {
    id: 'cost-discipleship',
    title: 'The Cost of Discipleship',
    author: 'Dietrich Bonhoeffer',
    description: 'A challenging examination of the Sermon on the Mount and what it means to follow Christ.',
    genre: 'Theology',
    topics: ['discipleship', 'theology'],
    coverColor: '#475569',
    url: 'https://www.goodreads.com/book/show/131913.The_Cost_of_Discipleship',
    quotes: [
      'When Christ calls a man, he bids him come and die.',
      'Cheap grace is the deadliest enemy of the Church.',
      'Costly grace is the gospel which must be sought again and again, the gift which must be asked for, the door at which a man must knock.',
    ],
  },
  {
    id: 'desiring-god',
    title: 'Desiring God',
    author: 'John Piper',
    description: 'Christian Hedonism — the idea that God is most glorified when we are most satisfied in Him.',
    genre: 'Theology',
    topics: ['theology', 'joy', 'worship'],
    coverColor: '#6366f1',
    url: 'https://www.goodreads.com/book/show/41429.Desiring_God',
    quotes: [
      'God is most glorified in us when we are most satisfied in Him.',
      'The great business of life is to glorify God by enjoying Him forever.',
      'God\'s passion for His glory and our passion for our joy are not at odds.',
    ],
  },
  {
    id: 'battlefield-mind',
    title: 'Battlefield of the Mind',
    author: 'Joyce Meyer',
    description: 'A practical guide to winning the battle in your mind through God\'s Word.',
    genre: 'Spiritual Warfare',
    topics: ['warfare', 'mind', 'healing'],
    coverColor: '#ef4444',
    url: 'https://www.goodreads.com/book/show/272138.Battlefield_of_the_Mind',
    quotes: [
      'You cannot have a positive life and a negative mind.',
      'The mind is the leader or forerunner of all actions.',
      'Think about what you\'re thinking about. Your thoughts will either defeat you or empower you.',
    ],
  },
  {
    id: 'whisper',
    title: 'Whisper',
    author: 'Mark Batterson',
    description: 'How to hear the voice of God through seven love languages of the Holy Spirit.',
    genre: 'Prayer',
    topics: ['prayer', 'hearing-god'],
    coverColor: '#06b6d4',
    url: 'https://www.goodreads.com/book/show/34649428-whisper',
    quotes: [
      'God is always speaking. The question is whether we\'re listening.',
      'Prayer is the difference between the best you can do and the best God can do.',
      'If you follow the still small voice, it will lead you to places you never dreamed possible.',
    ],
  },
  {
    id: 'power-praying-woman',
    title: 'The Power of a Praying Woman',
    author: 'Stormie Omartian',
    description: 'Prayers and insights for women seeking a deeper relationship with God.',
    genre: 'Prayer',
    topics: ['prayer', 'identity'],
    coverColor: '#06b6d4',
    url: 'https://www.goodreads.com/book/show/209040.The_Power_of_a_Praying_Woman',
    quotes: [
      'Prayer is acknowledging and experiencing the presence of God.',
      'Every time we pray we are given the opportunity to make a choice to put God first.',
      'The most important thing you can do for those you love is pray for them.',
    ],
  },
  {
    id: 'sit-walk-stand',
    title: 'Sit, Walk, Stand',
    author: 'Watchman Nee',
    description: 'An exposition of Ephesians revealing three postures of the Christian life.',
    genre: 'Bible Study',
    topics: ['identity', 'theology', 'discipleship'],
    coverColor: '#84cc16',
    url: 'https://www.goodreads.com/book/show/229906.Sit_Walk_Stand',
    quotes: [
      'God has blessed us with every spiritual blessing in the heavenly places in Christ.',
      'Our walk will always be the expression of our seated position.',
      'We do not fight for victory; we fight from victory.',
    ],
  },
  {
    id: 'prayer-keller',
    title: 'Prayer',
    author: 'Timothy Keller',
    description: 'Experiencing awe and intimacy with God, drawing on Augustine, Calvin, and Luther.',
    genre: 'Prayer',
    topics: ['prayer', 'devotional', 'theology'],
    coverColor: '#06b6d4',
    url: 'https://www.goodreads.com/book/show/18806014-prayer',
    quotes: [
      'Prayer is both conversation and encounter with God.',
      'To be loved but not known is comforting but superficial. To be known and not loved is our greatest fear. But to be fully known and truly loved is, well, a lot like being loved by God.',
      'If we pray only when we feel like it, prayer will be hit or miss.',
    ],
  },
  {
    id: 'prodigal-god',
    title: 'The Prodigal God',
    author: 'Timothy Keller',
    description: 'A fresh look at the parable of the prodigal son, revealing the true gospel of grace.',
    genre: 'Gospel',
    topics: ['grace', 'gospel', 'identity'],
    coverColor: '#f472b6',
    url: 'https://www.goodreads.com/book/show/4146940-the-prodigal-god',
    quotes: [
      'The gospel is this: We are more sinful and flawed in ourselves than we ever dared believe, yet at the very same time we are more loved and accepted than we ever dared hope.',
      'Jesus\' teaching consistently attracted the irreligious while offending the Bible-believing, institutional-religion people of his day.',
      'The father in the parable is not just waiting for his son to return; he is running toward him.',
    ],
  },
  {
    id: 'redeeming-love',
    title: 'Redeeming Love',
    author: 'Francine Rivers',
    description: 'The story of Hosea set in the California Gold Rush — a retelling of God\'s relentless love.',
    genre: 'Fiction',
    topics: ['grace', 'healing', 'identity'],
    coverColor: '#fb923c',
    url: 'https://www.goodreads.com/book/show/711526.Redeeming_Love',
    quotes: [
      'God is relentless in His pursuit of the ones He loves.',
      'You are worth more than you know. You are worth more than you were told.',
      'Love is not just a feeling. It\'s a choice you make over and over again.',
    ],
  },
  {
    id: 'pilgrims-progress',
    title: "Pilgrim's Progress",
    author: 'John Bunyan',
    description: 'The allegorical journey of Christian from the City of Destruction to the Celestial City.',
    genre: 'Classic',
    topics: ['discipleship', 'identity', 'theology'],
    coverColor: '#fbbf24',
    url: 'https://www.goodreads.com/book/show/29797.The_Pilgrim_s_Progress',
    quotes: [
      'He who would valiant be \'gainst all disaster, let him in constancy follow the Master.',
      'The entrance to the Celestial City is narrow, but the city itself is wide.',
      'Run, Christian, run! The prize is before you and the path is clear.',
    ],
  },
  {
    id: 'jesus-calling',
    title: 'Jesus Calling',
    author: 'Sarah Young',
    description: '365 daily devotional entries written as if Jesus is speaking directly to the reader.',
    genre: 'Devotional',
    topics: ['devotional', 'prayer', 'identity'],
    coverColor: '#f59e0b',
    url: 'https://www.goodreads.com/book/show/780277.Jesus_Calling',
    quotes: [
      'I am with you. These are the words I want you to hear above all others.',
      'Bring Me your weakness, and receive My strength.',
      'Peace is My continual gift to you. It flows abundantly from My throne of grace.',
    ],
  },
  {
    id: 'boundaries',
    title: 'Boundaries',
    author: 'Henry Cloud & John Townsend',
    description: 'When to say yes, how to say no, to take control of your life.',
    genre: 'Christian Living',
    topics: ['healing', 'identity', 'discipleship'],
    coverColor: '#34d399',
    url: 'https://www.goodreads.com/book/show/72537.Boundaries',
    quotes: [
      'Boundaries define us. They define what is me and what is not me.',
      'We are responsible to others and for ourselves.',
      'You are not responsible for the behavior of others, only your own response to it.',
    ],
  },
  {
    id: 'surprised-by-joy',
    title: 'Surprised by Joy',
    author: 'C.S. Lewis',
    description: 'Lewis\'s account of his spiritual journey from atheism to Christian faith.',
    genre: 'Memoir',
    topics: ['apologetics', 'theology', 'identity'],
    coverColor: '#a78bfa',
    url: 'https://www.goodreads.com/book/show/100920.Surprised_by_Joy',
    quotes: [
      'Joy is not a substitute for sex; sex is very often a substitute for Joy.',
      'I believe in Christianity as I believe that the sun has risen: not only because I see it, but because by it I see everything else.',
      'All Joy reminds. It is never a possession, always a desire for something longer ago or further away or still about to be.',
    ],
  },
  {
    id: 'experiencing-god',
    title: 'Experiencing God',
    author: 'Henry Blackaby',
    description: 'Knowing and doing the will of God through seven realities of experiencing Him.',
    genre: 'Devotional',
    topics: ['prayer', 'discipleship', 'hearing-god'],
    coverColor: '#f59e0b',
    url: 'https://www.goodreads.com/book/show/191641.Experiencing_God',
    quotes: [
      'Watch to see where God is at work and join Him.',
      'You cannot stay where you are and go with God at the same time.',
      'God speaks to His people. God speaks by the Holy Spirit through the Bible, prayer, circumstances, and the church.',
    ],
  },
  {
    id: 'the-shack',
    title: 'The Shack',
    author: 'William P. Young',
    description: 'A story of healing and encounter with the Trinity in the midst of unspeakable loss.',
    genre: 'Fiction',
    topics: ['grace', 'healing', 'theology'],
    coverColor: '#fb923c',
    url: 'https://www.goodreads.com/book/show/1152798.The_Shack',
    quotes: [
      'Pain has a way of clipping our wings and keeping us from being able to fly.',
      'I don\'t need to punish people for sin. Sin is its own punishment, devouring you from the inside.',
      'You are not defined by your past. You are prepared by your past.',
    ],
  },
];
